version: 2

updates:
  # ------------------------
  # NPM dependencies
  # ------------------------
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '07:00'
      timezone: 'UTC'

    open-pull-requests-limit: 10

    groups:
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'

      major:
        update-types:
          - 'major'

  # ------------------------
  # GitHub Actions
  # ------------------------
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '07:00'
      timezone: 'UTC'

    groups:
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'

      major:
        update-types:
          - 'major'
